trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  ciPipeline: 'ci-Function-API-master'
  functionAppName: 'fulfill3d-api-alpha'
  packageName: 'API'
  project: 'Fulfill3D'

resources:
  pipelines:
    - pipeline: ciFunctionAPIMaster
      source: 'ci-Function-API-master'
      trigger: true

steps:
  - template: ../../../DevOps/cd-dotNet8-AzureFunction-template.yml